[workspace]
members = ["macros"] 

[workspace.dependencies]
thiserror = {version = "1.0.58"}
macros = { package = "untwine_macros", path = "macros", version = "0.2.0" }

[package]
name = "untwine"
version = "0.3.1"
edition = "2021"
description = "Declarative parsing with a BNF-like syntax"
authors = ["boxbeam"]
keywords = ["parsing", "parser", "framework"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.48", features = ["full", "parsing", "extra-traits", "visit"] }
macros = { workspace = true }
thiserror = { workspace = true }
